### ISSUE TITLE
Stop using nose for testing as it is deprecated

### ISSUE THREAD

**Issue by Terseus** [netzulo/qacode#58]
As we can see in the [nose webpage](http://nose.readthedocs.io/en/latest/#note-to-users):

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

Personally I recommend py.test but it's up to you.

Keep in mind that this will not be a drop-in replacement as we're already using some `from nose.tools import ...` that needs to be changed when replacing nose with another testing tool.

**Comment by netzulo** [comment]
moved to #60
