### ISSUE TITLE
Simplify handle_command_selenium from qacode.py

### ISSUE THREAD

**Issue by Terseus** [netzulo/qacode#59]
The function `handle_command_selenium` from `qacode.py` is generating a critical issue in SonarQube: https://qalab.tk/issues/search#issues=AV54barUsvMKnvVatt31

The function is too complex, which makes it hard to maintain and easy to have bugs that no reasonable amount of testing would catch.

It should be splitted on smaller, more general functions, or maybe even its own class.

**Comment by netzulo** [comment]
are you refer to **qalab** instead of **qacode** ?

**Comment by netzulo** [comment]
moving issue to **qalab** project
